#!/usr/bin/env python3
"""Benchmarks for the signature-free ML-KEM anamorphic AKE paper.

The script produces the measurements required by Section 5 of the paper:

1. Protocol performance: ML-KEM, HKDF/HMAC, AEAD, complete AKE, ordinary
   records, anamorphic records, throughput, trials, and serialized sizes.
2. Anamorphic detectability: entropy, frequency, chi-square, KS/TV distance,
   classifier accuracy, balanced accuracy, and ROC-AUC.

No paper result is hard-coded.  Every CSV value is generated by the current
machine and the command-line configuration recorded in metadata.json.
"""

from __future__ import annotations

import argparse
import gc
import hashlib
import hmac
import json
import math
import platform
import secrets
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Callable, Iterable

import numpy as np
import pandas as pd
from scipy.stats import chisquare, entropy as scipy_entropy, ks_2samp

try:
    import oqs
except ImportError:  # Allows --help and static checks without liboqs-python.
    oqs = None

try:
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM
except ImportError:  # Allows --help and static checks without cryptography.
    AESGCM = None


HASH_LEN = 32
AUTH_KEY_LEN = 32
ENC_KEY_LEN = 32
EXPORT_KEY_LEN = 32


@dataclass(frozen=True)
class ExperimentConfig:
    kem_name: str
    runs: int
    warmup: int
    ell_values: tuple[int, ...]
    max_trials: int
    nonce_len: int
    cover_len: int
    security_samples: int
    records_per_session: int
    seed: int
    id_a_len: int
    id_b_len: int
    suite_len: int
    record_number_len: int
    content_type_len: int


def now_ns() -> int:
    return time.perf_counter_ns()


def parse_ell_values(value: str) -> tuple[int, ...]:
    values = tuple(sorted({int(item.strip()) for item in value.split(",") if item.strip()}))
    if not values or any(item < 1 or item > 16 for item in values):
        raise argparse.ArgumentTypeError("--ell-values must contain integers in [1, 16]")
    return values


def require_performance_dependencies() -> None:
    missing = []
    if oqs is None:
        missing.append("liboqs-python (module 'oqs')")
    if AESGCM is None:
        missing.append("cryptography")
    if missing:
        raise RuntimeError("Missing performance dependency/dependencies: " + ", ".join(missing))


def require_security_dependencies() -> None:
    try:
        import sklearn  # noqa: F401
    except ImportError as exc:
        raise RuntimeError(
            "Security classification requires scikit-learn. "
            "Install it in the experiment environment or run with --skip-security."
        ) from exc


def resolve_kem_name(requested: str) -> str:
    """Resolve the standardized name while supporting older liboqs aliases."""
    enabled = set(oqs.get_enabled_kem_mechanisms())
    candidates = [requested]
    if requested == "ML-KEM-768":
        candidates.extend(["Kyber768", "Kyber768-90s"])
    for candidate in candidates:
        if candidate in enabled:
            return candidate
    raise RuntimeError(
        f"No requested KEM is enabled. Tried {candidates}; "
        f"available mechanisms include: {sorted(enabled)[:20]}"
    )


def hkdf_sha256(ikm: bytes, salt: bytes, info: bytes, length: int) -> bytes:
    """RFC 5869 extract-and-expand using HMAC-SHA-256."""
    effective_salt = salt if salt else bytes(HASH_LEN)
    prk = hmac.new(effective_salt, ikm, hashlib.sha256).digest()
    output = bytearray()
    previous = b""
    counter = 1
    while len(output) < length:
        previous = hmac.new(prk, previous + info + bytes([counter]), hashlib.sha256).digest()
        output.extend(previous)
        counter += 1
    return bytes(output[:length])


def derive_working_keys(kem_secret: bytes, psk: bytes, transcript_hash: bytes) -> tuple[bytes, bytes, bytes]:
    material = hkdf_sha256(
        ikm=kem_secret + psk,
        salt=transcript_hash,
        info=b"signature-free-mlkem-ake-v1|auth|enc|export",
        length=AUTH_KEY_LEN + ENC_KEY_LEN + EXPORT_KEY_LEN,
    )
    return material[:AUTH_KEY_LEN], material[AUTH_KEY_LEN:AUTH_KEY_LEN + ENC_KEY_LEN], material[-EXPORT_KEY_LEN:]


def transcript_digest(id_a: bytes, id_b: bytes, n_a: bytes, n_b: bytes, ciphertext: bytes, suite: bytes) -> bytes:
    encoded = b"".join(
        len(field).to_bytes(4, "big") + field
        for field in (id_a, id_b, n_a, n_b, ciphertext, suite)
    )
    return hashlib.sha256(encoded).digest()


def confirmation_tag(auth_key: bytes, role: bytes, transcript_hash: bytes, prior_tag: bytes = b"") -> bytes:
    return hmac.new(auth_key, role + transcript_hash + prior_tag, hashlib.sha256).digest()


def prf_prefix(key: bytes, transcript_hash: bytes, record_number: int, nonce: bytes, ell: int) -> int:
    message = b"ano" + transcript_hash + record_number.to_bytes(8, "big") + nonce
    digest = hmac.new(key, message, hashlib.sha256).digest()
    return int.from_bytes(digest, "big") >> (len(digest) * 8 - ell)


def anamorphic_encode(
    key: bytes,
    transcript_hash: bytes,
    record_number: int,
    hidden_value: int,
    ell: int,
    nonce_len: int,
    max_trials: int,
) -> tuple[bytes, int]:
    for trial in range(1, max_trials + 1):
        nonce = secrets.token_bytes(nonce_len)
        if prf_prefix(key, transcript_hash, record_number, nonce, ell) == hidden_value:
            return nonce, trial
    raise RuntimeError(
        f"AnoEnc exceeded max_trials={max_trials} for ell={ell}. "
        "Increase --max-trials or reduce ell."
    )


def associated_data(
    transcript_hash: bytes,
    record_number: int,
    ell: int,
    record_number_len: int = 8,
    content_type: int = 1,
    content_type_len: int = 1,
) -> bytes:
    return (
        transcript_hash
        + record_number.to_bytes(record_number_len, "big")
        + content_type.to_bytes(content_type_len, "big")
        + bytes([ell])
    )


def compute_stats(samples_ms: Iterable[float]) -> dict[str, float]:
    values = np.asarray(list(samples_ms), dtype=float)
    if values.size == 0:
        raise ValueError("No timing samples were collected")
    std = float(np.std(values, ddof=1)) if values.size > 1 else 0.0
    mean = float(np.mean(values))
    return {
        "n": int(values.size),
        "mean_ms": mean,
        "std_ms": std,
        "median_ms": float(np.median(values)),
        "p95_ms": float(np.percentile(values, 95)),
        "ci95_ms": float(1.96 * std / math.sqrt(values.size)),
        "throughput_ops_s": float(1000.0 / mean) if mean > 0 else math.inf,
    }


def benchmark_callable(function: Callable[[], object], runs: int, warmup: int) -> dict[str, float]:
    for _ in range(warmup):
        function()
    samples = np.empty(runs, dtype=float)
    gc_was_enabled = gc.isenabled()
    gc.disable()
    try:
        for index in range(runs):
            start = now_ns()
            function()
            samples[index] = (now_ns() - start) / 1e6
    finally:
        if gc_was_enabled:
            gc.enable()
    return compute_stats(samples)


def stats_row(operation: str, stats: dict[str, float], **extra: object) -> dict[str, object]:
    return {"operation": operation, **stats, **extra}


def byte_distribution(nonces: list[bytes]) -> np.ndarray:
    flat = np.frombuffer(b"".join(nonces), dtype=np.uint8)
    return np.bincount(flat, minlength=256).astype(float)


def distribution_metrics(nonces: list[bytes]) -> dict[str, float]:
    counts = byte_distribution(nonces)
    probabilities = counts / counts.sum()
    nonzero = probabilities[probabilities > 0]
    chi = chisquare(counts)
    bits = np.unpackbits(np.frombuffer(b"".join(nonces), dtype=np.uint8))
    return {
        "shannon_entropy_bits_per_byte": float(scipy_entropy(nonzero, base=2)),
        "min_entropy_bits_per_byte": float(-math.log2(probabilities.max())),
        "bit_one_frequency": float(bits.mean()),
        "chi2_statistic": float(chi.statistic),
        "chi2_p_value": float(chi.pvalue),
    }


def nonce_features(nonces: list[bytes]) -> np.ndarray:
    matrix = np.frombuffer(b"".join(nonces), dtype=np.uint8).reshape(len(nonces), -1)
    return np.unpackbits(matrix, axis=1).astype(np.float64)


def numeric_projection(nonces: list[bytes]) -> np.ndarray:
    return np.asarray(
        [int.from_bytes(nonce[:8], "big") / float(1 << 64) for nonce in nonces],
        dtype=float,
    )


def classifier_metrics(
    normal_nonces: list[bytes],
    anamorphic_nonces: list[bytes],
    normal_groups: np.ndarray,
    anamorphic_groups: np.ndarray,
    seed: int,
) -> dict[str, float]:
    try:
        from sklearn.linear_model import LogisticRegression
        from sklearn.metrics import accuracy_score, balanced_accuracy_score, roc_auc_score
        from sklearn.model_selection import GroupShuffleSplit
    except ImportError as exc:
        raise RuntimeError(
            "Security classification requires scikit-learn. "
            "Install it in the experiment environment or run with --skip-security."
        ) from exc

    features = np.vstack((nonce_features(normal_nonces), nonce_features(anamorphic_nonces)))
    labels = np.concatenate((np.zeros(len(normal_nonces)), np.ones(len(anamorphic_nonces))))
    groups = np.concatenate((normal_groups, anamorphic_groups + normal_groups.max() + 1))

    first_split = GroupShuffleSplit(n_splits=1, train_size=0.70, random_state=seed)
    train_idx, remainder_idx = next(first_split.split(features, labels, groups))
    second_split = GroupShuffleSplit(n_splits=1, train_size=0.50, random_state=seed + 1)
    val_rel, test_rel = next(
        second_split.split(features[remainder_idx], labels[remainder_idx], groups[remainder_idx])
    )
    val_idx = remainder_idx[val_rel]
    test_idx = remainder_idx[test_rel]

    model = LogisticRegression(max_iter=1000, solver="liblinear", random_state=seed)
    model.fit(features[train_idx], labels[train_idx])
    val_prediction = model.predict(features[val_idx])
    test_prediction = model.predict(features[test_idx])
    test_score = model.predict_proba(features[test_idx])[:, 1]

    return {
        "classifier_validation_accuracy": float(accuracy_score(labels[val_idx], val_prediction)),
        "classifier_accuracy": float(accuracy_score(labels[test_idx], test_prediction)),
        "classifier_balanced_accuracy": float(balanced_accuracy_score(labels[test_idx], test_prediction)),
        "classifier_roc_auc": float(roc_auc_score(labels[test_idx], test_score)),
        "classifier_train_samples": int(train_idx.size),
        "classifier_validation_samples": int(val_idx.size),
        "classifier_test_samples": int(test_idx.size),
    }


def generate_security_dataset(
    mode: str,
    n_samples: int,
    records_per_session: int,
    ell: int,
    nonce_len: int,
    max_trials: int,
    rng: np.random.Generator,
) -> tuple[list[bytes], np.ndarray, list[int]]:
    nonces: list[bytes] = []
    groups: list[int] = []
    trials: list[int] = []
    session_id = 0
    while len(nonces) < n_samples:
        key = secrets.token_bytes(32)
        transcript_hash = secrets.token_bytes(32)
        for local_record in range(records_per_session):
            if len(nonces) >= n_samples:
                break
            record_number = session_id * records_per_session + local_record
            if mode == "normal":
                nonce, used_trials = secrets.token_bytes(nonce_len), 1
            else:
                hidden_value = int(rng.integers(0, 1 << ell))
                nonce, used_trials = anamorphic_encode(
                    key, transcript_hash, record_number, hidden_value,
                    ell, nonce_len, max_trials,
                )
            nonces.append(nonce)
            groups.append(session_id)
            trials.append(used_trials)
        session_id += 1
    return nonces, np.asarray(groups, dtype=int), trials


def run_security_experiments(config: ExperimentConfig, output_dir: Path) -> pd.DataFrame:
    require_security_dependencies()
    rows: list[dict[str, object]] = []
    rng = np.random.default_rng(config.seed)
    for ell in config.ell_values:
        print(f"[security] generating normal/anamorphic datasets for ell={ell}")
        normal, normal_groups, _ = generate_security_dataset(
            "normal", config.security_samples, config.records_per_session,
            ell, config.nonce_len, config.max_trials, rng,
        )
        anamorphic, anam_groups, ano_trials = generate_security_dataset(
            "anamorphic", config.security_samples, config.records_per_session,
            ell, config.nonce_len, config.max_trials, rng,
        )

        normal_metrics = distribution_metrics(normal)
        anam_metrics = distribution_metrics(anamorphic)
        normal_counts = byte_distribution(normal)
        anam_counts = byte_distribution(anamorphic)
        normal_p = normal_counts / normal_counts.sum()
        anam_p = anam_counts / anam_counts.sum()
        tv_distance = float(0.5 * np.abs(normal_p - anam_p).sum())
        ks = ks_2samp(numeric_projection(normal), numeric_projection(anamorphic), method="auto")
        classification = classifier_metrics(normal, anamorphic, normal_groups, anam_groups, config.seed)

        rows.append({
            "ell": ell,
            "samples_per_mode": config.security_samples,
            **{f"normal_{key}": value for key, value in normal_metrics.items()},
            **{f"anamorphic_{key}": value for key, value in anam_metrics.items()},
            "bit_frequency_absolute_difference": abs(
                normal_metrics["bit_one_frequency"] - anam_metrics["bit_one_frequency"]
            ),
            "ks_statistic": float(ks.statistic),
            "ks_p_value": float(ks.pvalue),
            "tv_distance": tv_distance,
            "anamorphic_mean_trials": float(np.mean(ano_trials)),
            "anamorphic_median_trials": float(np.median(ano_trials)),
            **classification,
        })

    dataframe = pd.DataFrame(rows)
    dataframe.to_csv(output_dir / "security_metrics.csv", index=False)
    return dataframe


def run_performance_experiments(config: ExperimentConfig, output_dir: Path) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    require_performance_dependencies()
    kem_name = resolve_kem_name(config.kem_name)
    print(f"[performance] using KEM mechanism: {kem_name}")

    id_a = b"A" * config.id_a_len
    id_b = b"B" * config.id_b_len
    suite = b"S" * config.suite_len
    psk = secrets.token_bytes(32)
    ano_key = secrets.token_bytes(32)
    cover_plaintext = secrets.token_bytes(config.cover_len)
    fixed_transcript_hash = secrets.token_bytes(32)
    fixed_auth_key = secrets.token_bytes(32)
    fixed_enc_key = secrets.token_bytes(32)
    fixed_nonce = secrets.token_bytes(config.nonce_len)
    fixed_aad = associated_data(
        fixed_transcript_hash, 0, config.ell_values[0],
        config.record_number_len, content_type_len=config.content_type_len,
    )
    aesgcm = AESGCM(fixed_enc_key)
    fixed_ciphertext = aesgcm.encrypt(fixed_nonce, cover_plaintext, fixed_aad)

    component_rows: list[dict[str, object]] = []
    protocol_rows: list[dict[str, object]] = []
    ano_rows: list[dict[str, object]] = []

    with oqs.KeyEncapsulation(kem_name) as bob_kem, oqs.KeyEncapsulation(kem_name) as sender_kem:
        public_key = bob_kem.generate_keypair()
        kem_ciphertext, kem_secret_sender = sender_kem.encap_secret(public_key)
        kem_secret_bob = bob_kem.decap_secret(kem_ciphertext)
        if kem_secret_sender != kem_secret_bob:
            raise RuntimeError("ML-KEM correctness check failed")

        component_rows.append(stats_row(
            "ML-KEM KeyGen",
            benchmark_callable(bob_kem.generate_keypair, config.runs, config.warmup),
        ))
        public_key = bob_kem.generate_keypair()

        def kem_encaps() -> tuple[bytes, bytes]:
            return sender_kem.encap_secret(public_key)

        component_rows.append(stats_row(
            "ML-KEM Encaps",
            benchmark_callable(kem_encaps, config.runs, config.warmup),
        ))
        kem_ciphertext, kem_secret_sender = sender_kem.encap_secret(public_key)

        component_rows.append(stats_row(
            "ML-KEM Decaps",
            benchmark_callable(lambda: bob_kem.decap_secret(kem_ciphertext), config.runs, config.warmup),
        ))

        component_rows.append(stats_row(
            "HKDF-SHA256",
            benchmark_callable(
                lambda: derive_working_keys(kem_secret_sender, psk, fixed_transcript_hash),
                config.runs, config.warmup,
            ),
        ))
        component_rows.append(stats_row(
            "HMAC-SHA256 tag",
            benchmark_callable(
                lambda: confirmation_tag(fixed_auth_key, b"B-finish", fixed_transcript_hash),
                config.runs, config.warmup,
            ),
        ))
        component_rows.append(stats_row(
            "AEAD encrypt",
            benchmark_callable(
                lambda: aesgcm.encrypt(secrets.token_bytes(config.nonce_len), cover_plaintext, fixed_aad),
                config.runs, config.warmup,
            ),
        ))
        component_rows.append(stats_row(
            "AEAD decrypt",
            benchmark_callable(
                lambda: aesgcm.decrypt(fixed_nonce, fixed_ciphertext, fixed_aad),
                config.runs, config.warmup,
            ),
        ))

        def authenticated_ake() -> None:
            n_a = secrets.token_bytes(16)
            ciphertext, sender_secret = sender_kem.encap_secret(public_key)
            bob_secret = bob_kem.decap_secret(ciphertext)
            n_b = secrets.token_bytes(16)
            digest = transcript_digest(id_a, id_b, n_a, n_b, ciphertext, suite)
            sender_auth, _, _ = derive_working_keys(sender_secret, psk, digest)
            bob_auth, _, _ = derive_working_keys(bob_secret, psk, digest)
            tau_b = confirmation_tag(bob_auth, b"B-finish", digest)
            if not hmac.compare_digest(tau_b, confirmation_tag(sender_auth, b"B-finish", digest)):
                raise RuntimeError("Bob confirmation failed")
            tau_a = confirmation_tag(sender_auth, b"A-finish", digest, tau_b)
            if not hmac.compare_digest(tau_a, confirmation_tag(bob_auth, b"A-finish", digest, tau_b)):
                raise RuntimeError("Alice confirmation failed")

        ake_stats = benchmark_callable(authenticated_ake, config.runs, config.warmup)
        component_rows.append(stats_row("Complete authenticated AKE", ake_stats))

        def ordinary_record() -> None:
            nonce = secrets.token_bytes(config.nonce_len)
            aad = associated_data(
                fixed_transcript_hash, 1, 0,
                config.record_number_len, content_type_len=config.content_type_len,
            )
            ciphertext = aesgcm.encrypt(nonce, cover_plaintext, aad)
            recovered = aesgcm.decrypt(nonce, ciphertext, aad)
            if recovered != cover_plaintext:
                raise RuntimeError("AEAD ordinary-record correctness failed")

        ordinary_stats = benchmark_callable(ordinary_record, config.runs, config.warmup)
        component_rows.append(stats_row("Ordinary protected record", ordinary_stats))

        kem_details = bob_kem.details
        kem_ct_len = int(kem_details["length_ciphertext"])
        aead_tag_len = len(fixed_ciphertext) - len(cover_plaintext)
        aad_len = len(fixed_aad)
        meta_len = config.id_a_len + config.id_b_len + config.suite_len
        ake_bytes = kem_ct_len + 16 + 16 + 2 * HASH_LEN + meta_len
        record_bytes = (
            config.record_number_len + config.nonce_len + config.cover_len
            + aead_tag_len + aad_len
        )

        protocol_rows.extend([
            {
                "configuration": "Authenticated AKE handshake",
                **ake_stats,
                "communication_bytes": ake_bytes,
                "ell": 0,
            },
            {
                "configuration": "Ordinary protected record",
                **ordinary_stats,
                "communication_bytes": record_bytes,
                "ell": 0,
            },
        ])

        for ell in config.ell_values:
            trial_samples: list[int] = []
            ano_enc_times: list[float] = []
            ano_dec_times: list[float] = []
            record_times: list[float] = []

            for index in range(config.warmup + config.runs):
                hidden_value = index % (1 << ell)
                start = now_ns()
                nonce, trials = anamorphic_encode(
                    ano_key, fixed_transcript_hash, index, hidden_value,
                    ell, config.nonce_len, config.max_trials,
                )
                enc_elapsed = (now_ns() - start) / 1e6

                aad = associated_data(
                    fixed_transcript_hash, index, ell,
                    config.record_number_len, content_type_len=config.content_type_len,
                )
                record_start = now_ns()
                ciphertext = aesgcm.encrypt(nonce, cover_plaintext, aad)
                recovered = aesgcm.decrypt(nonce, ciphertext, aad)
                decoded = prf_prefix(ano_key, fixed_transcript_hash, index, nonce, ell)
                record_elapsed = enc_elapsed + (now_ns() - record_start) / 1e6

                dec_start = now_ns()
                _ = prf_prefix(ano_key, fixed_transcript_hash, index, nonce, ell)
                dec_elapsed = (now_ns() - dec_start) / 1e6

                if recovered != cover_plaintext or decoded != hidden_value:
                    raise RuntimeError("Anamorphic record correctness failed")
                if index >= config.warmup:
                    trial_samples.append(trials)
                    ano_enc_times.append(enc_elapsed)
                    ano_dec_times.append(dec_elapsed)
                    record_times.append(record_elapsed)

            enc_stats = compute_stats(ano_enc_times)
            dec_stats = compute_stats(ano_dec_times)
            proposed_stats = compute_stats(record_times)
            covert_throughput = float(ell * proposed_stats["throughput_ops_s"])

            component_rows.append(stats_row(f"AnoEnc ell={ell}", enc_stats, ell=ell))
            component_rows.append(stats_row(f"AnoDec ell={ell}", dec_stats, ell=ell))
            ano_rows.append({
                "ell": ell,
                **{f"anoenc_{key}": value for key, value in enc_stats.items()},
                **{f"anodec_{key}": value for key, value in dec_stats.items()},
                "mean_trials": float(np.mean(trial_samples)),
                "median_trials": float(np.median(trial_samples)),
                "p95_trials": float(np.percentile(trial_samples, 95)),
                "theoretical_trials": float(2 ** ell),
                "covert_throughput_bits_s": covert_throughput,
                "record_mean_ms": proposed_stats["mean_ms"],
                "record_throughput_records_s": proposed_stats["throughput_ops_s"],
            })
            protocol_rows.append({
                "configuration": f"Anamorphic protected record (ell={ell})",
                **proposed_stats,
                "communication_bytes": record_bytes,
                "ell": ell,
            })

        communication = pd.DataFrame([
            {"item": "ML-KEM public key (pre-authenticated, not sent per session)", "bytes": int(kem_details["length_public_key"])},
            {"item": "ML-KEM ciphertext", "bytes": kem_ct_len},
            {"item": "AKE handshake", "bytes": ake_bytes},
            {"item": "Ordinary protected record", "bytes": record_bytes},
            {"item": "Anamorphic protected record", "bytes": record_bytes},
            {"item": "Anamorphic wire-format increment", "bytes": 0},
        ])

    components = pd.DataFrame(component_rows)
    protocols = pd.DataFrame(protocol_rows)
    anamorphic = pd.DataFrame(ano_rows)
    components.to_csv(output_dir / "component_benchmarks.csv", index=False)
    protocols.to_csv(output_dir / "protocol_summary.csv", index=False)
    anamorphic.to_csv(output_dir / "anamorphic_by_ell.csv", index=False)
    communication.to_csv(output_dir / "communication_sizes.csv", index=False)
    return components, protocols, anamorphic


def write_metadata(config: ExperimentConfig, output_dir: Path, resolved_kem: str | None) -> None:
    metadata = {
        "timestamp_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "python": platform.python_version(),
        "platform": platform.platform(),
        "processor": platform.processor(),
        "config": asdict(config),
        "resolved_kem": resolved_kem,
        "numpy": np.__version__,
        "pandas": pd.__version__,
        "oqs_python": getattr(oqs, "__version__", None) if oqs is not None else None,
    }
    (output_dir / "metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=Path("experimental_results"))
    parser.add_argument("--kem", default="ML-KEM-768")
    parser.add_argument("--runs", type=int, default=1000)
    parser.add_argument("--warmup", type=int, default=100)
    parser.add_argument("--ell-values", type=parse_ell_values, default=parse_ell_values("1,2,4,8"))
    parser.add_argument("--max-trials", type=int, default=65536)
    parser.add_argument("--nonce-len", type=int, default=12)
    parser.add_argument("--cover-len", type=int, default=256)
    parser.add_argument("--security-samples", type=int, default=2000)
    parser.add_argument("--records-per-session", type=int, default=10)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--id-a-len", type=int, default=16)
    parser.add_argument("--id-b-len", type=int, default=16)
    parser.add_argument("--suite-len", type=int, default=4)
    parser.add_argument("--record-number-len", type=int, default=8)
    parser.add_argument("--content-type-len", type=int, default=1)
    parser.add_argument("--skip-performance", action="store_true")
    parser.add_argument("--skip-security", action="store_true")
    return parser


def main() -> None:
    args = build_parser().parse_args()
    if args.runs < 2 or args.warmup < 0 or args.security_samples < 10:
        raise SystemExit("Use --runs >= 2, --warmup >= 0, and --security-samples >= 10")
    config = ExperimentConfig(
        kem_name=args.kem,
        runs=args.runs,
        warmup=args.warmup,
        ell_values=args.ell_values,
        max_trials=args.max_trials,
        nonce_len=args.nonce_len,
        cover_len=args.cover_len,
        security_samples=args.security_samples,
        records_per_session=args.records_per_session,
        seed=args.seed,
        id_a_len=args.id_a_len,
        id_b_len=args.id_b_len,
        suite_len=args.suite_len,
        record_number_len=args.record_number_len,
        content_type_len=args.content_type_len,
    )
    args.output_dir.mkdir(parents=True, exist_ok=True)

    resolved_kem = None
    if not args.skip_performance:
        require_performance_dependencies()
        resolved_kem = resolve_kem_name(config.kem_name)
        components, protocols, anamorphic = run_performance_experiments(config, args.output_dir)
        print("\nProtocol-performance summary:")
        print(protocols[["configuration", "mean_ms", "throughput_ops_s", "communication_bytes"]].to_string(index=False))
        print("\nAnamorphic performance by ell:")
        print(anamorphic[["ell", "anoenc_mean_ms", "mean_trials", "covert_throughput_bits_s"]].to_string(index=False))

    if not args.skip_security:
        security = run_security_experiments(config, args.output_dir)
        print("\nAnamorphic detectability summary:")
        print(security[["ell", "tv_distance", "ks_p_value", "classifier_accuracy", "classifier_roc_auc"]].to_string(index=False))

    write_metadata(config, args.output_dir, resolved_kem)
    print(f"\nAll generated data are in: {args.output_dir.resolve()}")


if __name__ == "__main__":
    main()